string ZpT = "p_{T}(Z) [GeV]", Zrap = "y(Z)", Zeta = "#eta(Z)";
string HT = "H_{T}(jets) [GeV]", Mjj = "M_{j_{1}j_{2}} [GeV]", jSpt = "#Delta_{pT}^{rel}(j_{1}j_{2})", jdPhi = "#Delta#phi(j_{1}j_{2})", jdEta = "#Delta#eta(j_{1}j_{2})";
string Mll = "M_{#mu#mu} [GeV]", leta = "#eta(#mu)", lpT = "p_{T}(#mu) [GeV]", ldPhi = "#Delta#phi(#mu_{1}#mu_{2})", ldEta = "#Delta#eta(#mu_{1}#mu_{2})", ldR = "#DeltaR(#mu_{1}#mu_{2})";
string lSpt = "#Delta_{pT}^{rel}(#mu_{1}#mu_{2})";
string Spt = "#Delta_{pT}^{rel}(j_{1}j_{2}#mu_{1}#mu_{2})";
string Sphi = "Sphi(j_{1}j_{2}#mu_{1}#mu_{2})";

int nJetPt_Zinc1jet(11);
double jetPt_Zinc1jet[12] = {30, 40, 52, 68, 88, 113, 144, 184, 234, 297, 377, 480};
int nJetPt_Zinc2jet(10);
double jetPt_Zinc2jet[11] = {30, 40, 52, 68, 88, 113, 144, 184, 234, 297, 377};
int nJetPt_Zinc3jet(7);
double jetPt_Zinc3jet[8] =  {30, 40, 52, 68, 88, 113, 144, 184};
int nJetPt_Zinc4jet(5);
double jetPt_Zinc4jet[6] =  {30, 40, 52, 68, 88, 113};
int nJetPt_Zinc5jet(4);
double jetPt_Zinc5jet[5] =  {30, 40, 52, 68, 88};
int nJetPtRatio_Zinc2jet(11);
//double jetPtRatio_Zinc2jet[12] = {};


int nJetHT_Zinc1jet(11);
double jetHT_Zinc1jet[12] = {30, 45, 65, 91, 125, 170, 230, 306, 406, 536, 707, 932};
int nJetHT_Zinc2jet(11);
double jetHT_Zinc2jet[12] = {60, 75, 95, 121, 155, 200, 260, 336, 436, 566, 737, 962};
int nJetHT_Zinc3jet(10);
double jetHT_Zinc3jet[11] = {90, 105, 125, 151, 185, 230, 290, 366, 466, 586, 767};
int nJetHT_Zinc4jet(9);
double jetHT_Zinc4jet[10] = {120, 140, 167, 203, 253, 320, 410, 530, 690, 910};
int nJetHT_Zinc5jet(7);
double jetHT_Zinc5jet[8] =  {150, 180, 222, 282, 365, 485, 650, 880};


if (leptonFlavor == "Electrons" || leptonFlavor == "DE" || leptonFlavor == "DE_") {
   Mll = "M_{ee} [GeV]";
   leta = "#eta(e)";
   lpT = "p_{T}(e) [GeV]";
   ldPhi = "#Delta#phi(e_{1}e_{2})";
   ldEta = "#Delta#eta(e_{1}e_{2})";
   ldR = "#DeltaR(e_{1}e_{2})";
   lSpt = "#Delta_{pT}^{rel}(e_{1}e_{2})";
   Spt = "#Delta_{pT}^{rel}(j_{1}j_{2}e_{1}e_{2})";
   Sphi = "Sphi(j_{1}j_{2}e_{1}e_{2})";
}
ostringstream name;
for (int i(0); i < numberPDFs; i++) {
name << "genZMass_Zinc0jet" << "_" << i; genZMass_Zinc0jet[i] = newHisto(name.str(), name.str(), Mll, 40, 71, 111);  name.str("");
name << "genZMass_Zinc1jet" << "_" << i; genZMass_Zinc1jet[i] = newHisto(name.str(), name.str(), Mll, 40, 71, 111);  name.str("");
name << "genZMass_Zinc2jet" << "_" << i; genZMass_Zinc2jet[i] = newHisto(name.str(), name.str(), Mll, 40, 71, 111);  name.str("");
name << "genZMass_Zinc3jet" << "_" << i; genZMass_Zinc3jet[i] = newHisto(name.str(), name.str(), Mll, 40, 71, 111);  name.str("");
name << "genZMass_Zinc4jet" << "_" << i; genZMass_Zinc4jet[i] = newHisto(name.str(), name.str(), Mll, 40, 71, 111);  name.str("");
name << "genZMass_Zinc5jet" << "_" << i; genZMass_Zinc5jet[i] = newHisto(name.str(), name.str(), Mll, 40, 71, 111);  name.str("");
name << "genZMass_Zinc6jet" << "_" << i; genZMass_Zinc6jet[i] = newHisto(name.str(), name.str(), Mll, 40, 71, 111);  name.str("");
name << "genZPt_Zinc0jet" << "_" << i; genZPt_Zinc0jet[i] = newHisto(name.str(), name.str(), ZpT, 40, 0, 200);  name.str("");
name << "genZPt_Zinc1jet" << "_" << i; genZPt_Zinc1jet[i] = newHisto(name.str(), name.str(), ZpT, 40, 0, 400);  name.str("");
name << "genZPt_Zinc2jet" << "_" << i; genZPt_Zinc2jet[i] = newHisto(name.str(), name.str(), ZpT, 40, 0, 400);  name.str("");
name << "genZPt_Zinc3jet" << "_" << i; genZPt_Zinc3jet[i] = newHisto(name.str(), name.str(), ZpT, 40, 0, 300);  name.str("");
name << "genZPt_Zinc4jet" << "_" << i; genZPt_Zinc4jet[i] = newHisto(name.str(), name.str(), ZpT, 40, 0, 200);  name.str("");
name << "genZPt_Zinc5jet" << "_" << i; genZPt_Zinc5jet[i] = newHisto(name.str(), name.str(), ZpT, 40, 0, 200);  name.str("");
name << "genZPt_Zinc6jet" << "_" << i; genZPt_Zinc6jet[i] = newHisto(name.str(), name.str(), ZpT, 40, 0, 200);  name.str("");
name << "genZRapidity_Zinc0jet" << "_" << i; genZRapidity_Zinc0jet[i] = newHisto(name.str(), name.str(), Zrap, 30,-3, 3);  name.str("");
name << "genZRapidity_Zinc1jet" << "_" << i; genZRapidity_Zinc1jet[i] = newHisto(name.str(), name.str(), Zrap, 30,-3, 3);  name.str("");
name << "genZRapidity_Zinc2jet" << "_" << i; genZRapidity_Zinc2jet[i] = newHisto(name.str(), name.str(), Zrap, 30,-3, 3);  name.str("");
name << "genZRapidity_Zinc3jet" << "_" << i; genZRapidity_Zinc3jet[i] = newHisto(name.str(), name.str(), Zrap, 30,-3, 3);  name.str("");
name << "genZRapidity_Zinc4jet" << "_" << i; genZRapidity_Zinc4jet[i] = newHisto(name.str(), name.str(), Zrap, 30,-3, 3);  name.str("");
name << "genZRapidity_Zinc5jet" << "_" << i; genZRapidity_Zinc5jet[i] = newHisto(name.str(), name.str(), Zrap, 30,-3, 3);  name.str("");
name << "genZRapidity_Zinc6jet" << "_" << i; genZRapidity_Zinc6jet[i] = newHisto(name.str(), name.str(), Zrap, 30,-3, 3);  name.str("");
name << "genZEta_Zinc0jet" << "_" << i; genZEta_Zinc0jet[i] = newHisto(name.str(), name.str(), Zeta, 30,-3, 3);  name.str("");
name << "genZEta_Zinc1jet" << "_" << i; genZEta_Zinc1jet[i] = newHisto(name.str(), name.str(), Zeta, 30,-3, 3);  name.str("");
name << "genZEta_Zinc2jet" << "_" << i; genZEta_Zinc2jet[i] = newHisto(name.str(), name.str(), Zeta, 30,-3, 3);  name.str("");
name << "genZEta_Zinc3jet" << "_" << i; genZEta_Zinc3jet[i] = newHisto(name.str(), name.str(), Zeta, 30,-3, 3);  name.str("");
name << "genZEta_Zinc4jet" << "_" << i; genZEta_Zinc4jet[i] = newHisto(name.str(), name.str(), Zeta, 30,-3, 3);  name.str("");
name << "genZEta_Zinc5jet" << "_" << i; genZEta_Zinc5jet[i] = newHisto(name.str(), name.str(), Zeta, 30,-3, 3);  name.str("");
name << "genZEta_Zinc6jet" << "_" << i; genZEta_Zinc6jet[i] = newHisto(name.str(), name.str(), Zeta, 30,-3, 3);  name.str("");
name << "genlepEta_Zinc0jet" << "_" << i; genlepEta_Zinc0jet[i] = newHisto(name.str(), name.str(), leta, 24,-2.4, 2.4);  name.str("");
name << "genlepEta_Zinc1jet" << "_" << i; genlepEta_Zinc1jet[i] = newHisto(name.str(), name.str(), leta, 24,-2.4, 2.4);  name.str("");
name << "genlepEta_Zinc2jet" << "_" << i; genlepEta_Zinc2jet[i] = newHisto(name.str(), name.str(), leta, 24,-2.4, 2.4);  name.str("");
name << "genFirstJetEta_Zinc1jet" << "_" << i; genFirstJetEta_Zinc1jet[i] = newHisto(name.str(), name.str(), "#eta(j_{1})", 24,-2.4, 2.4);  name.str("");
name << "genSecondJetEta_Zinc2jet" << "_" << i; genSecondJetEta_Zinc2jet[i] = newHisto(name.str(), name.str(), "#eta(j_{2})", 24,-2.4, 2.4);  name.str("");
name << "genThirdJetEta_Zinc3jet" << "_" << i; genThirdJetEta_Zinc3jet[i] = newHisto(name.str(), name.str(), "#eta(j_{3})", 16,-2.4, 2.4);  name.str("");
name << "genFourthJetEta_Zinc4jet" << "_" << i; genFourthJetEta_Zinc4jet[i] = newHisto(name.str(), name.str(), "#eta(j_{4})", 8,-2.4, 2.4);  name.str("");
name << "genFifthJetEta_Zinc5jet" << "_" << i; genFifthJetEta_Zinc5jet[i] = newHisto(name.str(), name.str(), "#eta(j_{5})", 4,-2.4, 2.4);  name.str("");
name << "genSixthJetEta_Zinc6jet" << "_" << i; genSixthJetEta_Zinc6jet[i] = newHisto(name.str(), name.str(), "#eta(j_{6})", 4,-2.4, 2.4);  name.str("");
name << "genlepPt_Zinc0jet" << "_" << i; genlepPt_Zinc0jet[i] = newHisto(name.str(), name.str(), lpT, 40, 0, 200);  name.str("");
name << "genlepPt_Zinc1jet" << "_" << i; genlepPt_Zinc1jet[i] = newHisto(name.str(), name.str(), lpT, 40, 0, 200);  name.str("");
name << "genlepPt_Zinc2jet" << "_" << i; genlepPt_Zinc2jet[i] = newHisto(name.str(), name.str(), lpT, 40, 0, 200);  name.str("");
name << "genSpTLeptons_Zexc2jet" << "_" << i; genSpTLeptons_Zexc2jet[i] = newHisto(name.str(), name.str(), lSpt, 50,0.,1.);  name.str("");
name << "genSpTLeptons_Zinc2jet" << "_" << i; genSpTLeptons_Zinc2jet[i] = newHisto(name.str(), name.str(), lSpt, 50, 0, 1);  name.str("");
name << "genJetsHT_Zinc1jet" << "_" << i; genJetsHT_Zinc1jet[i] = newHisto(name.str(), name.str(), HT, nJetHT_Zinc1jet, jetHT_Zinc1jet);  name.str("");
name << "genJetsHT_Zinc2jet" << "_" << i; genJetsHT_Zinc2jet[i] = newHisto(name.str(), name.str(), HT, nJetHT_Zinc2jet, jetHT_Zinc2jet);  name.str("");
name << "genJetsHT_Zinc3jet" << "_" << i; genJetsHT_Zinc3jet[i] = newHisto(name.str(), name.str(), HT, nJetHT_Zinc3jet, jetHT_Zinc3jet);  name.str("");
name << "genJetsHT_Zinc4jet" << "_" << i; genJetsHT_Zinc4jet[i] = newHisto(name.str(), name.str(), HT, nJetHT_Zinc4jet, jetHT_Zinc4jet);  name.str("");
name << "genJetsHT_Zinc5jet" << "_" << i; genJetsHT_Zinc5jet[i] = newHisto(name.str(), name.str(), HT, nJetHT_Zinc5jet, jetHT_Zinc5jet);  name.str("");
name << "genJetsHT_Zinc6jet" << "_" << i; genJetsHT_Zinc6jet[i] = newHisto(name.str(), name.str(), HT, nJetHT_Zinc5jet, jetHT_Zinc5jet);  name.str("");
name << "genFirstJetPt_Zinc1jet" << "_" << i; genFirstJetPt_Zinc1jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{1}) [GeV]", nJetPt_Zinc1jet, jetPt_Zinc1jet);  name.str("");
name << "genSecondJetPt_Zinc2jet" << "_" << i; genSecondJetPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{2}) [GeV]", nJetPt_Zinc2jet, jetPt_Zinc2jet);  name.str("");
name << "genThirdJetPt_Zinc3jet" << "_" << i; genThirdJetPt_Zinc3jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{3}) [GeV]", nJetPt_Zinc3jet, jetPt_Zinc3jet);  name.str("");
name << "genFourthJetPt_Zinc4jet" << "_" << i; genFourthJetPt_Zinc4jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{4}) [GeV]", nJetPt_Zinc4jet, jetPt_Zinc4jet);  name.str("");
name << "genFifthJetPt_Zinc5jet" << "_" << i; genFifthJetPt_Zinc5jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{5}) [GeV]", nJetPt_Zinc5jet, jetPt_Zinc5jet);  name.str("");
name << "genSixthJetPt_Zinc6jet" << "_" << i; genSixthJetPt_Zinc6jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{6}) [GeV]", nJetPt_Zinc5jet, jetPt_Zinc5jet);  name.str("");
name << "genRatioJetPt21_Zinc2jet" << "_" << i; genRatioJetPt21_Zinc2jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{2})/p_{T}(j_{1})", 10 , 0 , 1);  name.str("");
name << "genRatioJetPt32_Zinc3jet" << "_" << i; genRatioJetPt32_Zinc3jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{3})/p_{T}(j_{2})", 10 , 0 , 1);  name.str("");
name << "genFirstJetPt_Zexc1jet" << "_" << i; genFirstJetPt_Zexc1jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{1}) [GeV]", nJetPt_Zinc1jet, jetPt_Zinc1jet);  name.str("");
name << "genSecondJetPt_Zexc2jet" << "_" << i; genSecondJetPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{2}) [GeV]", nJetPt_Zinc2jet, jetPt_Zinc2jet);  name.str("");
name << "genFirstHighestJetPt_Zinc1jet" << "_" << i; genFirstHighestJetPt_Zinc1jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{1}) [GeV]", nJetPt_Zinc1jet, jetPt_Zinc1jet);  name.str("");
name << "genFirstHighestJetPt_Zinc2jet" << "_" << i; genFirstHighestJetPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{1}) [GeV]", nJetPt_Zinc2jet, jetPt_Zinc2jet);  name.str("");
name << "genFirstHighestJetPt_Zinc3jet" << "_" << i; genFirstHighestJetPt_Zinc3jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{1}) [GeV]", nJetPt_Zinc3jet, jetPt_Zinc3jet);  name.str("");
name << "genFirstHighestJetPt_Zinc4jet" << "_" << i; genFirstHighestJetPt_Zinc4jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{1}) [GeV]", nJetPt_Zinc4jet, jetPt_Zinc4jet);  name.str("");
name << "genFirstHighestJetPt_Zinc5jet" << "_" << i; genFirstHighestJetPt_Zinc5jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{1}) [GeV]", nJetPt_Zinc5jet, jetPt_Zinc5jet);  name.str("");
name << "genFirstHighestJetPt_Zinc6jet" << "_" << i; genFirstHighestJetPt_Zinc6jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{1}) [GeV]", nJetPt_Zinc5jet, jetPt_Zinc5jet);  name.str("");
name << "genSecondHighestJetPt_Zinc2jet" << "_" << i; genSecondHighestJetPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{2}) [GeV]", nJetPt_Zinc2jet, jetPt_Zinc2jet);  name.str("");
name << "genSecondHighestJetPt_Zinc3jet" << "_" << i; genSecondHighestJetPt_Zinc3jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{2}) [GeV]", nJetPt_Zinc3jet, jetPt_Zinc3jet);  name.str("");
name << "genSecondHighestJetPt_Zinc4jet" << "_" << i; genSecondHighestJetPt_Zinc4jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{2}) [GeV]", nJetPt_Zinc4jet, jetPt_Zinc4jet);  name.str("");
name << "genSecondHighestJetPt_Zinc5jet" << "_" << i; genSecondHighestJetPt_Zinc5jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{2}) [GeV]", nJetPt_Zinc5jet, jetPt_Zinc5jet);  name.str("");
name << "genSecondHighestJetPt_Zinc6jet" << "_" << i; genSecondHighestJetPt_Zinc6jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{2}) [GeV]", nJetPt_Zinc5jet, jetPt_Zinc5jet);  name.str("");
name << "genThirdHighestJetPt_Zinc3jet" << "_" << i; genThirdHighestJetPt_Zinc3jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{3}) [GeV]", nJetPt_Zinc3jet, jetPt_Zinc3jet);  name.str("");
name << "genThirdHighestJetPt_Zinc4jet" << "_" << i; genThirdHighestJetPt_Zinc4jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{3}) [GeV]", nJetPt_Zinc4jet, jetPt_Zinc4jet);  name.str("");
name << "genThirdHighestJetPt_Zinc5jet" << "_" << i; genThirdHighestJetPt_Zinc5jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{3}) [GeV]", nJetPt_Zinc5jet, jetPt_Zinc5jet);  name.str("");
name << "genThirdHighestJetPt_Zinc6jet" << "_" << i; genThirdHighestJetPt_Zinc6jet[i] = newHisto(name.str(), name.str(), "p_{T}(j_{3}) [GeV]", nJetPt_Zinc5jet, jetPt_Zinc5jet);  name.str("");
name << "genTwoJetsPtDiff_Zexc2jet" << "_" << i; genTwoJetsPtDiff_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta pT(j_{1}j_{2}) [GeV]", 10,  0, 100);  name.str("");
name << "genJetsMass_Zexc2jet" << "_" << i; genJetsMass_Zexc2jet[i] = newHisto(name.str(), name.str(), Mjj, 24, 20, 620);  name.str("");
name << "genptBal_Zexc2jet" << "_" << i; genptBal_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Sigma pT [GeV]", 50,  0, 100);  name.str("");
name << "gendPhiJets_Zexc2jet" << "_" << i; gendPhiJets_Zexc2jet[i] = newHisto(name.str(), name.str(), jdPhi, 20,  0, PI);  name.str("");
name << "gendEtaJets_Zexc2jet" << "_" << i; gendEtaJets_Zexc2jet[i] = newHisto(name.str(), name.str(), jdEta, 50, -5, 5);  name.str("");
name << "gendEtaFirstJetZ_Zexc2jet" << "_" << i; gendEtaFirstJetZ_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta#eta(j_{1}Z)", 50, -5, 5);  name.str("");
name << "gendEtaSecondJetZ_Zexc2jet" << "_" << i; gendEtaSecondJetZ_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta#eta(j_{2}Z)", 50, -5, 5);  name.str("");
name << "gendEtaJet1Plus2Z_Zexc2jet" << "_" << i; gendEtaJet1Plus2Z_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta#eta(j_{12}Z)", 50, -5, 5);  name.str("");
name << "genPHI_Zexc2jet" << "_" << i; genPHI_Zexc2jet[i] = newHisto(name.str(), name.str(), "#phi(j_{12}Z)", 25,  0, PI);  name.str("");
name << "genPHI_T_Zexc2jet" << "_" << i; genPHI_T_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta S(j_{12}Z)", 10,  0, PI);  name.str("");
name << "genSpT_Zexc2jet" << "_" << i; genSpT_Zexc2jet[i] = newHisto(name.str(), name.str(), Spt, 20,  0, 1);  name.str("");
name << "genSpTJets_Zexc2jet" << "_" << i; genSpTJets_Zexc2jet[i] = newHisto(name.str(), name.str(), jSpt, 20,  0, 1);  name.str("");
name << "genSPhi_Zexc2jet" << "_" << i; genSPhi_Zexc2jet[i] = newHisto(name.str(), name.str(), Sphi, 50,  0, PI);  name.str("");
name << "genTwoJetsPtDiff_Zinc2jet" << "_" << i; genTwoJetsPtDiff_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta pT(j_{1}j_{2}) [GeV]", 10,  0, 100);  name.str("");
name << "genBestTwoJetsPtDiff_Zinc2jet" << "_" << i; genBestTwoJetsPtDiff_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta pT(j_{1}j_{2}) [GeV]", 10,  0, 100);  name.str("");
name << "genJetsMass_Zinc2jet" << "_" << i; genJetsMass_Zinc2jet[i] = newHisto(name.str(), name.str(), Mjj, 24, 20, 620);  name.str("");
name << "genBestJetsMass_Zinc2jet" << "_" << i; genBestJetsMass_Zinc2jet[i] = newHisto(name.str(), name.str(), Mjj, 24, 20, 620);  name.str("");
name << "genptBal_Zinc2jet" << "_" << i; genptBal_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Sigma pT [GeV]", 50,  0, 100);  name.str("");
name << "gendPhiJets_Zinc2jet" << "_" << i; gendPhiJets_Zinc2jet[i] = newHisto(name.str(), name.str(), jdPhi, 20,  0, PI);  name.str("");
name << "genBestdPhiJets_Zinc2jet" << "_" << i; genBestdPhiJets_Zinc2jet[i] = newHisto(name.str(), name.str(), jdPhi, 20,  0, PI);  name.str("");
name << "gendEtaJets_Zinc2jet" << "_" << i; gendEtaJets_Zinc2jet[i] = newHisto(name.str(), name.str(), jdEta, 50, -5, 5);  name.str("");
name << "gendEtaFirstJetZ_Zinc2jet" << "_" << i; gendEtaFirstJetZ_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta#eta(j_{1}Z)", 50, -5, 5);  name.str("");
name << "gendEtaSecondJetZ_Zinc2jet" << "_" << i; gendEtaSecondJetZ_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta#eta(j_{2}Z)", 50, -5, 5);  name.str("");
name << "gendEtaJet1Plus2Z_Zinc2jet" << "_" << i; gendEtaJet1Plus2Z_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta#eta(j_{12}Z)", 50, -5, 5);  name.str("");
name << "genPHI_Zinc2jet" << "_" << i; genPHI_Zinc2jet[i] = newHisto(name.str(), name.str(), "#phi(j_{12}Z)", 25,  0, PI);  name.str("");
name << "genBestPHI_Zinc2jet" << "_" << i; genBestPHI_Zinc2jet[i] = newHisto(name.str(), name.str(), "#phi(j_{12}Z)", 25,  0, PI);  name.str("");
name << "genPHI_T_Zinc2jet" << "_" << i; genPHI_T_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta S(j_{12}Z)", 10,  0, PI);  name.str("");
name << "genBestPHI_T_Zinc2jet" << "_" << i; genBestPHI_T_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta S(j_{12}Z)", 10,  0, PI);  name.str("");
name << "genSpT_Zinc2jet" << "_" << i; genSpT_Zinc2jet[i] = newHisto(name.str(), name.str(), Spt, 20,  0, 1);  name.str("");
name << "genBestSpT_Zinc2jet" << "_" << i; genBestSpT_Zinc2jet[i] = newHisto(name.str(), name.str(), Spt, 20,  0, 1);  name.str("");
name << "genSpTJets_Zinc2jet" << "_" << i; genSpTJets_Zinc2jet[i] = newHisto(name.str(), name.str(), jSpt, 20,  0, 1);  name.str("");
name << "genBestSpTJets_Zinc2jet" << "_" << i; genBestSpTJets_Zinc2jet[i] = newHisto(name.str(), name.str(), jSpt, 20,  0, 1);  name.str("");
name << "genSPhi_Zinc2jet" << "_" << i; genSPhi_Zinc2jet[i] = newHisto(name.str(), name.str(), Sphi, 50,  0, PI);  name.str("");
name << "genBestSPhi_Zinc2jet" << "_" << i; genBestSPhi_Zinc2jet[i] = newHisto(name.str(), name.str(), Sphi, 50,  0, PI);  name.str("");
name << "genTwoJetsPtDiff_LowPt_Zexc2jet" << "_" << i; genTwoJetsPtDiff_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta pT(j_{1}j_{2}) [GeV]", 10,  0, 100);  name.str("");
name << "genJetsMass_LowPt_Zexc2jet" << "_" << i; genJetsMass_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), Mjj, 24, 20, 620);  name.str("");
name << "genptBal_LowPt_Zexc2jet" << "_" << i; genptBal_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Sigma pT [GeV]", 50, 0, 100);  name.str("");
name << "gendPhiJets_LowPt_Zexc2jet" << "_" << i; gendPhiJets_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), jdPhi, 15, 0, PI);  name.str("");
name << "gendPhiLeptons_LowPt_Zexc2jet" << "_" << i; gendPhiLeptons_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), ldPhi, 50, 0, PI);  name.str("");
name << "genPHI_LowPt_Zexc2jet" << "_" << i; genPHI_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#phi(j_{12}Z)", 25, 0, PI);  name.str("");
name << "genPHI_T_LowPt_Zexc2jet" << "_" << i; genPHI_T_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta S(j_{12}Z)", 10, 0, PI);  name.str("");
name << "genSpT_LowPt_Zexc2jet" << "_" << i; genSpT_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), Spt, 25, 0, 1);  name.str("");
name << "genSpTJets_LowPt_Zexc2jet" << "_" << i; genSpTJets_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), jSpt, 15, 0, 1);  name.str("");
name << "genSpTLeptons_LowPt_Zexc2jet" << "_" << i; genSpTLeptons_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), lSpt, 50, 0, 1);  name.str("");
name << "genSPhi_LowPt_Zexc2jet" << "_" << i; genSPhi_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), Sphi, 50, 0, PI);  name.str("");
name << "genTwoJetsPtDiff_LowPt_Zinc2jet" << "_" << i; genTwoJetsPtDiff_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta pT(j_{1}j_{2}) [GeV]", 10,  0, 100);  name.str("");
name << "genBestTwoJetsPtDiff_LowPt_Zinc2jet" << "_" << i; genBestTwoJetsPtDiff_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta pT(j_{1}j_{2}) [GeV]", 10,  0, 100);  name.str("");
name << "genJetsMass_LowPt_Zinc2jet" << "_" << i; genJetsMass_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), Mjj, 24, 20, 620);  name.str("");
name << "genBestJetsMass_LowPt_Zinc2jet" << "_" << i; genBestJetsMass_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), Mjj, 24, 20, 620);  name.str("");
name << "genptBal_LowPt_Zinc2jet" << "_" << i; genptBal_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Sigma pT [GeV]", 50, 0, 100);  name.str("");
name << "gendPhiJets_LowPt_Zinc2jet" << "_" << i; gendPhiJets_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), jdPhi, 15, 0, PI);  name.str("");
name << "genBestdPhiJets_LowPt_Zinc2jet" << "_" << i; genBestdPhiJets_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), jdPhi, 15, 0, PI);  name.str("");
name << "gendPhiLeptons_LowPt_Zinc2jet" << "_" << i; gendPhiLeptons_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), ldPhi, 50, 0, PI);  name.str("");
name << "genPHI_LowPt_Zinc2jet" << "_" << i; genPHI_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#phi(j_{12}Z)", 25, 0, PI);  name.str("");
name << "genBestPHI_LowPt_Zinc2jet" << "_" << i; genBestPHI_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#phi(j_{12}Z)", 25, 0, PI);  name.str("");
name << "genPHI_T_LowPt_Zinc2jet" << "_" << i; genPHI_T_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta S(j_{12}Z)", 10, 0, PI);  name.str("");
name << "genBestPHI_T_LowPt_Zinc2jet" << "_" << i; genBestPHI_T_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta S(j_{12}Z)", 10, 0, PI);  name.str("");
name << "genSpT_LowPt_Zinc2jet" << "_" << i; genSpT_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), Spt, 25, 0, 1);  name.str("");
name << "genBestSpT_LowPt_Zinc2jet" << "_" << i; genBestSpT_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), Spt, 25, 0, 1);  name.str("");
name << "genSpTJets_LowPt_Zinc2jet" << "_" << i; genSpTJets_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), jSpt, 15, 0, 1);  name.str("");
name << "genBestSpTJets_LowPt_Zinc2jet" << "_" << i; genBestSpTJets_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), jSpt, 15, 0, 1);  name.str("");
name << "genSpTLeptons_LowPt_Zinc2jet" << "_" << i; genSpTLeptons_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), lSpt, 50, 0, 1);  name.str("");
name << "genSPhi_LowPt_Zinc2jet" << "_" << i; genSPhi_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), Sphi, 50, 0, PI);  name.str("");
name << "genBestSPhi_LowPt_Zinc2jet" << "_" << i; genBestSPhi_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), Sphi, 50, 0, PI);  name.str("");
name << "genPHI_LowSpT_LowPt_Zexc2jet" << "_" << i; genPHI_LowSpT_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#phi", 25,0.,PI);  name.str("");
name << "genSPhi_LowSpT_LowPt_Zexc2jet" << "_" << i; genSPhi_LowSpT_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "S_{#phi}", 50,2.5,PI);  name.str("");
name << "genPHI_LowSpT_LowPt_Zinc2jet" << "_" << i; genPHI_LowSpT_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#phi", 25,0.,PI);  name.str("");
name << "genSPhi_LowSpT_LowPt_Zinc2jet" << "_" << i; genSPhi_LowSpT_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "S_{#phi}", 50,2.5,PI);  name.str("");
name << "genPHI_HighSpT_LowPt_Zexc2jet" << "_" << i; genPHI_HighSpT_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#phi", 50,0.,PI);  name.str("");
name << "genSPhi_HighSpT_LowPt_Zexc2jet" << "_" << i; genSPhi_HighSpT_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "S_{#phi}", 50,0.,PI);  name.str("");
name << "genPHI_HighSpT_LowPt_Zinc2jet" << "_" << i; genPHI_HighSpT_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#phi", 50,0.,PI);  name.str("");
name << "genSPhi_HighSpT_LowPt_Zinc2jet" << "_" << i; genSPhi_HighSpT_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "S_{#phi}", 50,0.,PI);  name.str("");
name << "genSpT_LowSPhi_LowPt_Zexc2jet" << "_" << i; genSpT_LowSPhi_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genSpT_LowSPhi_LowPt_Zinc2jet" << "_" << i; genSpT_LowSPhi_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genSpT_HighSPhi_LowPt_Zexc2jet" << "_" << i; genSpT_HighSPhi_LowPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genSpT_HighSPhi_LowPt_Zinc2jet" << "_" << i; genSpT_HighSPhi_LowPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genptBal_HighPt_Zexc2jet" << "_" << i; genptBal_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Sigma pT [GeV]", 50,0.,100.);  name.str("");
name << "gendPhiJets_HighPt_Zexc2jet" << "_" << i; gendPhiJets_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), jdPhi, 15, 0, PI);  name.str("");
name << "gendPhiLeptons_HighPt_Zexc2jet" << "_" << i; gendPhiLeptons_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), ldPhi, 50,0.,PI);  name.str("");
name << "genPHI_HighPt_Zexc2jet" << "_" << i; genPHI_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#phi", 50,0.,PI);  name.str("");
name << "genPHI_T_HighPt_Zexc2jet" << "_" << i; genPHI_T_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta S", 10,0.,PI);  name.str("");
name << "genSpT_HighPt_Zexc2jet" << "_" << i; genSpT_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genSpTJets_HighPt_Zexc2jet" << "_" << i; genSpTJets_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 15,0.,1.);  name.str("");
name << "genSpTLeptons_HighPt_Zexc2jet" << "_" << i; genSpTLeptons_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genSPhi_HighPt_Zexc2jet" << "_" << i; genSPhi_HighPt_Zexc2jet[i] = newHisto(name.str(), name.str(), "S_{#phi}", 50,0.,PI);  name.str("");
name << "genptBal_HighPt_Zinc2jet" << "_" << i; genptBal_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Sigma pT [GeV]", 50,0.,100.);  name.str("");
name << "gendPhiJets_HighPt_Zinc2jet" << "_" << i; gendPhiJets_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), jdPhi, 15, 0, PI);  name.str("");
name << "gendPhiLeptons_HighPt_Zinc2jet" << "_" << i; gendPhiLeptons_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), ldPhi, 50,0.,PI);  name.str("");
name << "genPHI_HighPt_Zinc2jet" << "_" << i; genPHI_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#phi", 50,0.,PI);  name.str("");
name << "genPHI_T_HighPt_Zinc2jet" << "_" << i; genPHI_T_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta S", 10,0.,PI);  name.str("");
name << "genSpT_HighPt_Zinc2jet" << "_" << i; genSpT_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genSpTJets_HighPt_Zinc2jet" << "_" << i; genSpTJets_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 15,0.,1.);  name.str("");
name << "genSpTLeptons_HighPt_Zinc2jet" << "_" << i; genSpTLeptons_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genSPhi_HighPt_Zinc2jet" << "_" << i; genSPhi_HighPt_Zinc2jet[i] = newHisto(name.str(), name.str(), "S_{#phi}", 50,0.,PI);  name.str("");
name << "gendPhiJetsDeltaR_Zexc2jet" << "_" << i; gendPhiJetsDeltaR_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta#phi", 50,0.,PI);  name.str("");
name << "genPHI_TDeltaR_Zexc2jet" << "_" << i; genPHI_TDeltaR_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta S", 50,0.,PI);  name.str("");
name << "genSpTJetsDeltaR_Zexc2jet" << "_" << i; genSpTJetsDeltaR_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genSpTDeltaR_Zexc2jet" << "_" << i; genSpTDeltaR_Zexc2jet[i] = newHisto(name.str(), name.str(), "#Delta_{pT}^{rel}", 50,0.,1.);  name.str("");
name << "genZNGoodJets_Zinc" << "_" << i; genZNGoodJets_Zinc[i] = newHisto(name.str(), name.str(), "N_{jets}", 8, -0.5, 7.5);  name.str("");
name << "genZNGoodJets_Zexc" << "_" << i; genZNGoodJets_Zexc[i] = newHisto(name.str(), name.str(), "N_{jets}", 8, -0.5, 7.5);  name.str("");
name << "gendeltaRjetMu" << "_" << i; gendeltaRjetMu[i] = newHisto(name.str(), name.str(), "#R", 50, 0., 2.5);  name.str("");
}
